sql = '''
SELECT
"BUSINESS_UNIT_ID" , 
"TRANSFER_ID" , 
"TRANSFER_OCCURENCE_TYPE" , 
"TRANSFER_ORIGIN_NAME" , 
"FROM_SITE_ID" , 
"TO_SITE_ID" , 
"TRANSFER_TYPE" , 
"DISTRIBUTION_ID" , 
"ACTIVITY_TYPE" , 
"CREATION_DATE" , 
"STATUS" , 
"PROCESSED_DATE", 
"USERNAME" , 
"FROM_BUSINESS_UNIT_ID", 
"TO_BUSINESS_UNIT_ID", 
"WMS_FLAG", 
"WMS_PROCESSED_DATE"
FROM
TRANSFERS_ACTIVITY
'''