merge ='''
                INSERT INTO XFR_MERCH_TRANSFERS
                 (
                        "BUSINESS_UNIT_ID" , 
                        "TRANSFER_ID" , 
                        "REQUEST_TRANSFER_ID" , 
                        "TRANSFER_OCCURENCE_TYPE" , 
                        "TRANSFER_TYPE" , 
                        "TRANSFER_DATE" , 
                        "REASON_SUB_TYPE" , 
                        "REASON_ID" , 
                        "SHIP_VIA_ID" , 
                        "CANCELLED_IND" , 
                        "UPDATED_IND" , 
                        "FROM_SITE_ID" , 
                        "TO_SITE_ID" , 
                        "TRANSFER_ORIGIN_NAME" , 
                        "ITEM_QTY" , 
                        "QTY_PREPACK_EXPL" , 
                        "JOB_ID" , 
                        "AUDIT_LIST_PRINTED_IND" , 
                        "CREATED_BY_USERNAME" , 
                        "SVS_BUSINESS_UNIT_ID" , 
                        "REMARK_KEY" , 
                        "CREATION_DATE" , 
                        "PROCESSED_DATE" , 
                        "FROM_BUSINESS_UNIT_ID" , 
                        "TO_BUSINESS_UNIT_ID" , 
                        "ORIGIN_ID" , 
                        "DC_TRANSFER_ID" , 
                        "SHIPPING_INFO" , 
                        "DC_SHIPPING_DATE" , 
                        "ACTIVATION_DATE" , 
                        "ADDRESS_ID" , 
                        "ADDRESS_TYPE_ID" , 
                        "CARTON_ID" , 
                        "TRANSFER_GROUP_ID" , 
                        "POSTED_PERIOD_YEAR" , 
                        "POSTED_PERIOD" , 
                        "POSTED_YEAR" , 
                        "POSTED_WEEK" , 
                        "TO_POSTED_PERIOD_YEAR" , 
                        "TO_POSTED_PERIOD" , 
                        "TO_POSTED_YEAR" , 
                        "TO_POSTED_WEEK" , 
                        "DATE_UPDATED" , 
                        "CANCELLED_PERIOD_YEAR", 
                        "CANCELLED_PERIOD" , 
                        "CANCELLED_YEAR" , 
                        "CANCELLED_WEEK" , 
                        "TO_CANCELLED_PERIOD_YEAR" , 
                        "TO_CANCELLED_PERIOD" , 
                        "TO_CANCELLED_YEAR" , 
                        "TO_CANCELLED_WEEK" , 
                        "DATE_CANCELLED" , 
                        "TRANSFER_SEQUENCE_ID" , 
                        "TRANSFER_ALL_IND" , 
                        "TRANSFER_COMPLETE_IND" , 
                        "REQUEST_CREATED_BY_USERNAME" , 
                        "COMMENTS" , 
                        "WEB_ORDER_ID" , 
                        "RMA_CODE" 
                 )
                 SELECT
                 src.$1,
                 src.$2,
                 src.$3,
                 src.$4,
                 src.$5,
                 src.$6,
                 src.$7,
                 src.$8,
                 src.$9,
                 src.$10,
                 src.$11,
                 src.$12,
                 src.$13,
                 src.$14,
                 src.$15,
                 src.$16,
                 src.$17,
                 src.$18,
                 src.$19,
                 src.$20,
                 src.$21,
                 src.$22,
                 src.$23,
                 src.$24,
                 src.$25,
                 src.$26,
                 src.$27,
                 src.$28,
                 src.$29,
                 src.$30,
                 src.$31,
                 src.$32,
                 src.$33,
                 src.$34,
                 src.$35,
                 src.$36,
                 src.$37,
                 src.$38,
                 src.$39,
                 src.$40,
                 src.$41,
                 src.$42,
                 src.$43,
                 src.$44,
                 src.$45,
                 src.$46,
                 src.$47,
                 src.$48,
                 src.$49,
                 src.$50,
                 src.$51,
                 src.$52,
                 src.$53,
                 src.$54,
                 src.$55,
                 src.$56,
                 src.$57,
                 src.$58,
                 src.$59
                 FROM @{v_sf_stage}/{file}( FILE_FORMAT => csv_file_format) src; '''